# Generated by Django 5.0 on 2023-12-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('postalCode', models.CharField(max_length=15)),
                ('territory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productCode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=70)),
                ('productScale', models.CharField(max_length=10)),
                ('productVendor', models.CharField(max_length=50)),
                ('productDescription', models.TextField()),
                ('quantityInStock', models.SmallIntegerField()),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MSRP', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('productLine', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('textDescription', models.TextField(blank=True, null=True)),
                ('htmlDescription', models.TextField()),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('jobTitle', models.CharField(max_length=50)),
                ('reportsTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.employee')),
                ('officeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.office')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=50)),
                ('contactLastName', models.CharField(max_length=50)),
                ('contactFirstName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('creditLimit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('salesRepEmployeeNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('requiredDate', models.DateField()),
                ('shippedDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField()),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkNumber', models.CharField(max_length=50)),
                ('paymentDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOrdered', models.IntegerField()),
                ('priceEach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderLineNumber', models.SmallIntegerField()),
                ('orderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('productCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productLine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productline'),
        ),
    ]
