# Generated by Django 5.0 on 2023-12-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='officeCode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productLine',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='ProductLine',
        ),
    ]
