# Generated by Django 5.0 on 2023-12-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_employee_officecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='MSRP',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productScale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productVendor',
        ),
    ]
